name: 'Pipe Line Part One'

on:
  workflow_dispatch:

jobs:
  job_one:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Display Message
      run: |
        echo 'Pipe Line Part One Triggered'
